Document: zurl
Title: Debian zurl Manual
Author: <insert document author here>
Abstract: This manual describes what zurl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zurl/zurl.sgml.gz

Format: postscript
Files: /usr/share/doc/zurl/zurl.ps.gz

Format: text
Files: /usr/share/doc/zurl/zurl.text.gz

Format: HTML
Index: /usr/share/doc/zurl/html/index.html
Files: /usr/share/doc/zurl/html/*.html
